### ISSUE TITLE
Add brightness / saturation feature

### ISSUE THREAD

**Issue by fabiocaccamo** [maxkonovalov/MKGradientView#1]
Is it in your todo?

**Comment by maxkonovalov** [comment]
Hey Fabio,
Brightness/saturation as such doesn't apply directly to gradients. Maybe you could give some more details on what exactly you would like to achieve?
You can also try setting gradient colors using `UIColor(hue: h, saturation: s, brightness: b, alpha: a)` if it helps.

**Comment by fabiocaccamo** [comment]
Hi Max, 
I imagine I could use your lib for a color picker, and it would be useful to have getters/setters to control saturation and brightness of the whole gradient before choosing a color.

**Comment by maxkonovalov** [comment]
The gradient generating algorithm behind `MKGradientView` is not quite suitable for dynamically changing colors (it takes some time to render the gradient image), please see [Performance section in Readme](https://github.com/maxkonovalov/MKGradientView#performance). 
If that's not the case for you and the algorithm is fast enough for your needs, you can use the following extension:

``` swift
extension MKGradientView {

    /** Change `saturation` value for all gradient colors **/
    func updateColorsSaturation(saturation: CGFloat) {
        colors = colors.map { color in
            var h: CGFloat = 0.0
            var s: CGFloat = 0.0
            var b: CGFloat = 0.0
            var a: CGFloat = 0.0
            color.getHue(&h, saturation: &s, brightness: &b, alpha: &a)
            return UIColor(hue: h, saturation: saturation, brightness: b, alpha: a)
        }
    }

    /** Change `brightness` value for all gradient colors **/
    func updateColorsBrightness(brightness: CGFloat) {
        colors = colors.map { color in
            var h: CGFloat = 0.0
            var s: CGFloat = 0.0
            var b: CGFloat = 0.0
            var a: CGFloat = 0.0
            color.getHue(&h, saturation: &s, brightness: &b, alpha: &a)
            return UIColor(hue: h, saturation: s, brightness: brightness, alpha: a)
        }
    }

}
```

The code above simply modifies `brightness` and `saturation` values for all gradient colors. You can modify it for more sophisticated color manipulations.

Another approach could be to fake brightness and saturation by simply laying out your gradient view above solid-color black or white view and changing its alpha.

**Comment by fabiocaccamo** [comment]
I understand the performance problem. 
Thanks for the extension!
