### ISSUE TITLE
Color distribution according to percentage?

### ISSUE THREAD

**Issue by AbidHussainCom** [maxkonovalov/MKGradientView#2]
I'm trying to achieve a 3-colored gradient view where color distribution can be configured. I understand that your view & CGGradientLayer both have locations property but I'm still not able to achieve the results needed. 
I'm trying to achieve this: http://i.stack.imgur.com/HN73s.png
For further details http://stackoverflow.com/questions/33788533/swift-2-1-cagradientlayer-color-location-distribution

Can you help me achieve this?

**Comment by maxkonovalov** [comment]
Hello Abid,
Please see my SO answer: http://stackoverflow.com/a/33800041/3160561
Hope it helps you to achieve what you need. For simple linear gradients I'd recommend to use `CAGradientLayer`, as it allows to animate its values.
