### ISSUE TITLE
Crash with release build on Xcode 11.4

### ISSUE THREAD

**Issue by yosoycody** [maxkonovalov/MKGradientView#8]
I'm seeing a crash that I can only reproduce on the release build. Running on simulator does not result in a crash. Here's the info:

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000112b54020
MKGradientView
MKGradientGenerator.swift - Line 58
specialized static GradientGenerator.gradientImage(type:size:colors:colors2:locations:locations2:startPoint:endPoint:startPoint2:endPoint2:scale:) + 58

Any ideas? This just started happening when building app with latest Xcode 11.4.

**Comment by maxkonovalov** [comment]
@yosoycody this is fixed in [v2.0.2](https://github.com/maxkonovalov/MKGradientView/releases/tag/2.0.2)
